---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gputest
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/giantswarm/gputest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gputest
  namespace: default
spec:
  interval: 1m
  path: ./
  postBuild:
    substitute:
      cluster_name: gputest
      organization: martin
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gputest
  timeout: 2m
