---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gputest-apps
  namespace: default
spec:
  interval: 1m
  path: ./apps
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
      organization: martin
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gputest
  timeout: 2m
