global:
  connectivity:
    network:
      vpcCidr: 10.0.0.0/16
    subnets:
      - cidrBlocks:
          - cidr: 10.0.32.0/19
            availabilityZone: b
          - cidr: 10.0.64.0/19
            availabilityZone: d
          - cidr: 10.0.96.0/19
            availabilityZone: f
        isPublic: false
      - cidrBlocks:
          - cidr: 10.0.0.0/24
            availabilityZone: b
          - cidr: 10.0.1.0/24
            availabilityZone: d
          - cidr: 10.0.2.0/24
            availabilityZone: f
        isPublic: true
  metadata:
    name: ${cluster_name}
    organization: ${organization}
    preventDeletion: false
  nodePools:
    nodepool0:
      availabilityZones:
        - us-east-1b
        - us-east-1d
        - us-east-1f
      instanceType: m5.xlarge
      maxSize: 3
      minSize: 1
      rootVolumeSizeGB: 8
    gpu-worker-pool-1:
      availabilityZones:
        - us-east-1b
        - us-east-1f
      instanceType: p5.48xlarge
      maxSize: 1
      minSize: 1
      rootVolumeSizeGB: 15
      instanceWarmup: 600
      minHealthyPercentage: 90
      spotInstances:
        enabled: true
        maxPrice: 30
      customNodeTaints:
        - key: "nvidia.com/gpu"
          value: "Exists"
          effect: "NoSchedule"
  providerSpecific:
    region: us-east-1
  release:
    version: "${release}"
